#!/usr/bin/env bash
./configure --with-plugin uptime --with-plugin mem --with-plugin cpu --with-plugin process --with-plugin heartbeat --with-plugin logs --with-plugin start --dest-cpu x64
gmake || make
